---
title: "FinalProject"
author: "Jana Nassir"
date: "11/20/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
income <- read_csv("~/finalp/datasets/crime.csv")
```
```{r}
library(readr)
income <- read_csv("~/finalp/datasets/income.csv")
```

```{r}
library(readr)
education_finance <- read_csv("~/finalp/datasets/education_finance.csv", 
    col_types = cols(YEAR = col_number(), 
        ENROLL = col_number(), TOTAL_REVENUE = col_number(), 
        TOTAL_EXPENDITURE = col_number()))
```

```{r}
income <- filter(income, !is.na(State))
```

```{r}
crimes <- filter(crime, year>=1984)
```

```{r}
yearly_income <- gather(income, year, income, 2:38) 
```

```{r}
crimes <- rename(crimes, state = state_name)
```
```{r}
crime <- rename(crime, state = state_name)
```


```{r}
yearly_income <- rename(yearly_income, state = State)
```

```{r}
yearly_income$year <- as.numeric(yearly_income$year)
```

```{r}
crime_dataset <- full_join (crimes, yearly_income, by = c("state", "year"))
```

```{r cars}
yearly_unemployment <- gather(unemployment, year, unemployment, 2:40)
```

```{r}
yearly_unemployment$year <- as.numeric(yearly_unemployment$year)
```

```{r}
yearly_unemployment <- filter(yearly_unemployment, year>=1984)
```

```{r}
crime_dataset <- full_join (crime_dataset, yearly_unemployment, by = c("state", "year"))
```

```{r}
crime_dataset <- filter(crime_dataset, year<=2019)
```

```{r}
crime_dataset <- subset (crime_dataset, select = -c(rape_revised, caveats))
```

```{r}
crime <- subset (crime, select = -c(rape_revised, caveats))
```


```{r}
crime_dataset_edu <- crime_dataset
```

```{r}
crime_dataset_edu <- filter(crime_dataset_edu, year >= 2008)
```

```{r}
crime_dataset_edu <- full_join (crime_dataset_edu, edu_attainment, by = c("state", "year"))
```

```{r}
crime$state[is.na(crime$state)] <- "United States"
crimes$state[is.na(crimes$state)] <- "United States"
crime_dataset_edu$state[is.na(crime_dataset_edu$state)] <- "United States"
crime_dataset$state[is.na(crime_dataset$state)] <- "United States"

crime$state_abbr[is.na(crime$state_abbr)] <- "USA"
crimes$state_abbr[is.na(crimes$state_abbr)] <- "USA"
crime_dataset_edu$state_abbr[is.na(crime_dataset_edu$state_abbr)] <- "USA"
crime_dataset$state_abbr[is.na(crime_dataset$state_abbr)] <- "USA"
```

```{r}

```


